export const AUTH = 'AuthScreen'
export const ABOUT = 'AboutScreen'
export const HOME = 'HomeScreen'
export const USER_AREA = 'UserAreaStackScreen'
export const CREATE_ACCOUNT = 'CreateAccountScreen'
export const WORKOUT_AREA = 'WorkoutAreaScreen'
export const WORKOUT_STACK = 'WorkoutAreaStackScreen'
export const EDIT_WORKOUT = 'EditWorkoutScreen'
